### PR TITLE
Update fanatical version

### PR DESCRIPTION
**Pull request by borancar**
Fixes issues with login to Fanatical.

### CODE REVIEW

**Comment by Slashbunny** [comment]
See #18 and #19 . This will cause the downloader to re-download the `fanatical` plugin every time it runs because the `0.0.2` release's `manifest.json` wasn't updated by the author (it still shows `0.0.1`).

**Comment by borancar** [comment]
Ouch, sorry about it :disappointed:, and especially for raising the issue for the third time. Let me try contacting the author of the fanatical plugin.

**Comment by borancar** [comment]
https://github.com/nosyn00b/GOG2_Fanatical_Plugin/pull/2

**Comment by milroneth** [comment]
The manifest has just been updated, thanks @borancar for the pull request.
This can now be accepted without issues as well!

**Comment by Slashbunny** [comment]
I think he'll need to do another release, since the existing `fanatical_v0.0.2.zip` is from June and still has `0.0.1` as the version 😢

**Comment by Slashbunny** [comment]
I changed the manifest to pull the `zip` file from the latest commit (with the version fix) instead of downloading the release in 3bcdd94d28350b1710c715e38d241446e01d1343 . That should solve the issue.

**Pull request closed without merging**
